language: node_js

notifications:
  email:
    on_success: never

jobs:
  include:
    - stage: "PHP"
      name: "PHPStan on PS nightly"
      language: php
      php: 7.2
      script:
        - composer install
        # PHP Stan
        - docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:nightly
        - docker exec -ti temp-ps rm -rf /var/www/html/modules/ps_qualityassurance
        - docker run --rm --volumes-from temp-ps -v $PWD:/var/www/html/modules/ps_qualityassurance -e _PS_ROOT_DIR_=/var/www/html quetzacoalt/phpstan analyse --configuration=/var/www/html/modules/ps_qualityassurance/tests/php/phpstan/phpstan.neon

